#!/bin/bash

TIMESTAMP=`date +"%F-%T"`
XIWI_ROOT=/opt/pscp
XIWI_PROG=$XIWI_ROOT/xiwi
XIWI_LOG=$XIWI_ROOT/logs
LOG=$XIWI_LOG/wombat-${TIMESTAMP}.log

$XIWI_PROG/wombat/wombat -fcgi :9100 > $LOG &
disown
