#!/bin/bash

TIMESTAMP=`date +"%F-%T"`
XIWI_META=$XIWI_ROOT/data/meta
XIWI_LOG=$XIWI_ROOT/logs
XIWI_SERVER=$XIWI_ROOT/paperscape-webserver/webserver
XIWI_SERVER_SET=$XIWI_ROOT/paperscape-webserver/config/arxiv-settings.json
LOG=$XIWI_LOG/wombat.log

$XIWI_SERVER/webserver --settings $XIWI_CONFIG --fcgi :9100 --log-file $LOG --meta $XIWI_META &
disown
