#!/bin/sh

function usage {
    echo "$0: usage:"
    echo "  specify directory path of tiles"

}

if [ $# -lt 1 ]
then
	usage;	
	exit
fi

files=`find $1 -type f -name "*.png"`

for f in $files
do
    if [ "${f:(-5)}" != "g.png" ]; then
        newFile="${f:0:(-4)}g.png" 
        convert -type Grayscale $f $newFile
    fi
done
