#!/bin/sh

function usage {
    echo "$0: usage:"
    echo "  specify directory path of zones"
}

if [ $# -lt 1 ]
then
	usage;	
	exit
fi

find $1 -type f -name "*.json" | xargs --max-proc=`nproc` -n 1 gzip -kf
