#!/bin/bash

DB=localhost
DEST_DIR=/srv/pscp-tiles/www/

go build

#nice ./tiles --db $DB --sub-cats --db-suffix r0000c2048 $DEST_DIR/world_r0000c2048
#nice ./tiles --db $DB --sub-cats --db-suffix r0001c2048 $DEST_DIR/world_r0001c2048
#nice ./tiles --db $DB --sub-cats --db-suffix rnilc2048 $DEST_DIR/world_rnilc2048
#nice ./tiles --db $DB --sub-cats --db-suffix r1000c0000 $DEST_DIR/world_r1000c0000

nice ./tiles --db $DB --db-suffix hep_r1000c0000 $DEST_DIR/world_hep_r1000c0000
nice ./tiles --db $DB --db-suffix hep_r0001c2048 $DEST_DIR/world_hep_r0001c2048

#nice ./tiles --db $DB --sub-cats --db-suffix r0001c0001 $DEST_DIR/world_r0001c0001
#nice ./tiles --db $DB --sub-cats --db-suffix r0001c0032 $DEST_DIR/world_r0001c0032
#nice ./tiles --db $DB --sub-cats --db-suffix r0001c0256 $DEST_DIR/world_r0001c0256
#nice ./tiles --db $DB --sub-cats --db-suffix r0001c1024 $DEST_DIR/world_r0001c1024
#nice ./tiles --db $DB --sub-cats --db-suffix r0001c4096 $DEST_DIR/world_r0001c4096
#nice ./tiles --db $DB --sub-cats --db-suffix r0032c0001 $DEST_DIR/world_r0032c0001
#nice ./tiles --db $DB --sub-cats --db-suffix r0032c0032 $DEST_DIR/world_r0032c0032
#nice ./tiles --db $DB --sub-cats --db-suffix r0032c0256 $DEST_DIR/world_r0032c0256
#nice ./tiles --db $DB --sub-cats --db-suffix r0032c1024 $DEST_DIR/world_r0032c1024
#nice ./tiles --db $DB --sub-cats --db-suffix r0032c4096 $DEST_DIR/world_r0032c4096
#nice ./tiles --db $DB --sub-cats --db-suffix r0256c0001 $DEST_DIR/world_r0256c0001
#nice ./tiles --db $DB --sub-cats --db-suffix r0256c0032 $DEST_DIR/world_r0256c0032
#nice ./tiles --db $DB --sub-cats --db-suffix r0256c0256 $DEST_DIR/world_r0256c0256
#nice ./tiles --db $DB --sub-cats --db-suffix r0256c1024 $DEST_DIR/world_r0256c1024
#nice ./tiles --db $DB --sub-cats --db-suffix r0256c4096 $DEST_DIR/world_r0256c4096
#nice ./tiles --db $DB --sub-cats --db-suffix r1024c0001 $DEST_DIR/world_r1024c0001
#nice ./tiles --db $DB --sub-cats --db-suffix r1024c0032 $DEST_DIR/world_r1024c0032
#nice ./tiles --db $DB --sub-cats --db-suffix r1024c0256 $DEST_DIR/world_r1024c0256
#nice ./tiles --db $DB --sub-cats --db-suffix r1024c1024 $DEST_DIR/world_r1024c1024
#nice ./tiles --db $DB --sub-cats --db-suffix r1024c4096 $DEST_DIR/world_r1024c4096
